[package]
name = "lazy_json"
description = "lexer and parser"
version = "0.0.0"
authors = ["mnmun <mnmnmun@proton.me>"]
homepage = "https://github.com/mnmun/json"
repository = "https://github.com/mnmun/json"
readme = "README.md"
exclude = ["flake.nix", "flake.lock"]
license = "MIT"
edition = "2024"

[dependencies]
a_bc = { git = "https://github.com/mnmun/a_bc", branch = "main" }
getset = "0.1.7"
lazy_tree = { git = "https://github.com/mnmun/lazy_tree", branch = "main" }

[dev-dependencies]
pretty_assertions = "1.4.1"
